import { ModuleInfo, ModuleKey } from "@santrios/types";

export const SANTRIOS_MODULES: Record<ModuleKey, ModuleInfo> = {
  CORE: {
    id: "mod-core",
    key: "CORE",
    name: "Modul Inti & Dashboard",
    description: "Fondasi sistem, multi-tenant, otentikasi, manajemen pengguna, dan ringkasan operasional.",
    icon: "LayoutDashboard",
    isCore: true,
    isActive: true,
  },
  SANTRI: {
    id: "mod-santri",
    key: "SANTRI",
    name: "Data Santri",
    description: "Manajemen data induk santri, profil lengkap, NIS, kelas, kamar, dan riwayat santri.",
    icon: "Users",
    isCore: false,
    isActive: true,
  },
  KEUANGAN: {
    id: "mod-keuangan",
    key: "KEUANGAN",
    name: "Keuangan & Tagihan",
    description: "Manajemen pos tagihan, invoice pembayaran SPP, kas masuk/keluar, dan laporan saldo.",
    icon: "CreditCard",
    isCore: false,
    isActive: true,
  },
  ABSENSI: {
    id: "mod-absensi",
    key: "ABSENSI",
    name: "Absensi & Presensi",
    description: "Pencatatan kehadiran harian cepat untuk shalat berjamaah, sekolah, dan kegiatan asrama.",
    icon: "CalendarCheck",
    isCore: false,
    isActive: true,
  },
  TAHFIZH: {
    id: "mod-tahfizh",
    key: "TAHFIZH",
    name: "Tahfizh Al-Qur'an",
    description: "Pelacakan setoran hafalan baru, muraja'ah, target juz, visualisasi progress, dan catatan musyrif.",
    icon: "BookOpen",
    isCore: false,
    isActive: true,
  },
  AKADEMIK: {
    id: "mod-akademik",
    key: "AKADEMIK",
    name: "Akademik & Sekolah",
    description: "Struktur tahun ajaran, semester, mata pelajaran, jadwal pelajaran, penilaian, dan raport santri.",
    icon: "GraduationCap",
    isCore: false,
    isActive: true,
  },
  ASRAMA: {
    id: "mod-asrama",
    key: "ASRAMA",
    name: "Manajemen Asrama",
    description: "Pengelolaan gedung, alokasi kamar santri, kapasitas, musyrif pembina, dan mutasi kamar.",
    icon: "Home",
    isCore: false,
    isActive: true,
  },
  PERIZINAN: {
    id: "mod-perizinan",
    key: "PERIZINAN",
    name: "Perizinan Santri",
    description: "Alur perizinan santri (pulang/keluar) bertingkat dari wali, musyrif, hingga pimpinan keamanan.",
    icon: "FileCheck",
    isCore: false,
    isActive: true,
  },
  WALI_SANTRI: {
    id: "mod-wali",
    key: "WALI_SANTRI",
    name: "Portal Wali Santri",
    description: "Akses informasi bagi orang tua santri: absensi, tahfizh, nilai, dan pembayaran tagihan.",
    icon: "UserCheck",
    isCore: false,
    isActive: true,
  },
  PPDB: {
    id: "mod-ppdb",
    key: "PPDB",
    name: "PPDB Online",
    description: "Penerimaan santri baru: formulir pendaftaran daring, ujian seleksi, verifikasi berkas, dan konversi ke santri aktif.",
    icon: "UserPlus",
    isCore: false,
    isActive: true,
  },
  INVENTARIS: {
    id: "mod-inventaris",
    key: "INVENTARIS",
    name: "Inventaris Aset",
    description: "Pencatatan aset barang pesantren, kondisi fisik, lokasi ruangan, dan pencatatan mutasi/peminjaman.",
    icon: "Package",
    isCore: false,
    isActive: true,
  },
  KOPERASI: {
    id: "mod-koperasi",
    key: "KOPERASI",
    name: "Koperasi & Kantin",
    description: "Point of sales (kasir), stok produk, limit belanja kartu santri, dan laporan penjualan harian.",
    icon: "ShoppingCart",
    isCore: false,
    isActive: true,
  },
  ALUMNI: {
    id: "mod-alumni",
    key: "ALUMNI",
    name: "Database Alumni",
    description: "Pendataan alumni pesantren, tahun kelulusan, jejak studi lanjutan, profesi, dan jejaring komunitas.",
    icon: "Award",
    isCore: false,
    isActive: true,
  },
};

export const ALL_MODULE_KEYS = Object.keys(SANTRIOS_MODULES) as ModuleKey[];
